// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNlGlMJzwqfWSAi2ZxSyqHNGmPS2dAm7c',
    appId: '1:549924956745:web:82b7c7e7977ebeeee9ad98',
    messagingSenderId: '549924956745',
    projectId: 'fbconnection-3757d',
    authDomain: 'fbconnection-3757d.firebaseapp.com',
    storageBucket: 'fbconnection-3757d.firebasestorage.app',
    measurementId: 'G-7XZY5SPK3K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0Qlu5UDW3fff-EVUZBRm4xyoogze93qc',
    appId: '1:549924956745:android:41ab2e561c898988e9ad98',
    messagingSenderId: '549924956745',
    projectId: 'fbconnection-3757d',
    storageBucket: 'fbconnection-3757d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBaiA_4sALxe2ps3iuynDqCMmiqZUAXUAY',
    appId: '1:549924956745:ios:5b8ff4ab54e425aee9ad98',
    messagingSenderId: '549924956745',
    projectId: 'fbconnection-3757d',
    storageBucket: 'fbconnection-3757d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBaiA_4sALxe2ps3iuynDqCMmiqZUAXUAY',
    appId: '1:549924956745:ios:5b8ff4ab54e425aee9ad98',
    messagingSenderId: '549924956745',
    projectId: 'fbconnection-3757d',
    storageBucket: 'fbconnection-3757d.firebasestorage.app',
    iosBundleId: 'com.example.firebaseConnection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBNlGlMJzwqfWSAi2ZxSyqHNGmPS2dAm7c',
    appId: '1:549924956745:web:c69629be7e34a71ce9ad98',
    messagingSenderId: '549924956745',
    projectId: 'fbconnection-3757d',
    authDomain: 'fbconnection-3757d.firebaseapp.com',
    storageBucket: 'fbconnection-3757d.firebasestorage.app',
    measurementId: 'G-Y8TDRWYGKQ',
  );
}
